name: ci
on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

defaults:
  run:
    shell: bash

jobs:
  arm:
    runs-on: [self-hosted, Linux, ARM64]
    strategy:
      fail-fast: true
      matrix:
        arch: [arm64v8]
    steps:
      - uses: docker://hasufell/arm64v8-ubuntu-haskell:focal
        name: Cleanup
        with:
          args: "find . -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +"

      - name: Checkout code
        uses: actions/checkout@v3

      - if: matrix.arch == 'arm64v8'
        uses: docker://hasufell/arm64v8-ubuntu-haskell:focal
        name: Run build (arm64v8 linux)
        with:
          args: sh -c "cabal update && env && autoreconf -i && head config.sub && cabal test all --test-show-details=direct"

